[build-system]
requires = ["setuptools", "Cython"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
packages = []

[project]
name = "reversi"
version = "0.0.1"
dependencies = [
    "cython"
]