[build-system]
requires = ["setuptools==80.9.0", "cython==3.1.2"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
packages = []

[project]
name = "reversi"
version = "0.0.1"
dependencies = [
    "cython==3.1.2", "pygame==2.6.1"
]